// Rules data, independently expressed as declarative effects. No upstream
// resolver code or game artwork is distributed. Component audit: docs/components.md.
export const TRACKS = [
  {
    id: 1,
    length: 10,
    marks: [
      [5, "X"],
      [1, "Z"],
    ],
  },
  {
    id: 2,
    length: 11,
    marks: [
      [8, "X"],
      [1, "Z"],
    ],
  },
  {
    id: 3,
    length: 12,
    marks: [
      [8, "X"],
      [3, "Y"],
      [1, "Z"],
    ],
  },
  {
    id: 4,
    length: 13,
    marks: [
      [9, "X"],
      [5, "Y"],
      [1, "Z"],
    ],
  },
  {
    id: 5,
    length: 14,
    marks: [
      [11, "X"],
      [7, "Y"],
      [1, "Z"],
    ],
  },
  {
    id: 6,
    length: 15,
    marks: [
      [10, "X"],
      [7, "Y"],
      [3, "Y"],
      [1, "Z"],
    ],
  },
  {
    id: 7,
    length: 16,
    marks: [
      [12, "X"],
      [8, "Y"],
      [5, "Y"],
      [1, "Z"],
    ],
  },
];
const attack = (amount, zones = "own", mode = "normal") => ({
  type: "attack",
  amount,
  zones,
  mode,
});
const heal = (amount) => ({ type: "heal", amount });
const change = (stat, amount) => ({ type: "change", stat, amount });
const flag = (name) => ({ type: "flag", name });
function external(id, name, shield, hp, speed, xyz, traits = {}) {
  const serious = id.startsWith("S"),
    difficulty = Number(id.match(/\d/)[0]);
  return {
    id,
    name,
    position: "external",
    severity: serious ? "serious" : "normal",
    difficulty,
    expansion: Number(id.split("-")[1]) > 100,
    shield,
    hp,
    speed,
    points: serious
      ? difficulty === 1
        ? [4, 8]
        : difficulty === 2
          ? [6, 12]
          : [8, 16]
      : difficulty === 1
        ? [2, 4]
        : difficulty === 2
          ? [3, 6]
          : [4, 8],
    effects: Object.fromEntries(
      ["X", "Y", "Z"].map((x, i) => [
        x,
        Array.isArray(xyz[i]) ? xyz[i] : xyz[i] ? [xyz[i]] : [],
      ]),
    ),
    ...traits,
  };
}
export const THREATS = [
  external("E1-01", "Pulse Ball", 1, 5, 2, [
    attack(1, "all"),
    attack(2, "all"),
    attack(2, "all"),
  ]),
  external("E1-02", "Destroyer", 2, 5, 2, [
    attack(1, "own", "double"),
    attack(2, "own", "double"),
    attack(2, "own", "double"),
  ]),
  external(
    "E1-03",
    "Stealth Fighter",
    2,
    4,
    3,
    [flag("revealed"), attack(2), attack(2)],
    { stealth: true },
  ),
  external(
    "E1-04",
    "Energy Cloud",
    3,
    5,
    2,
    [
      { type: "drain", system: "shield", zones: "all" },
      attack(1, "other"),
      attack(2, "other"),
    ],
    { pulseBreaksShield: true },
  ),
  external("E1-05", "Gunship", 2, 5, 2, [attack(2), attack(2), attack(3)]),
  external(
    "E1-06",
    "Cryoshield Fighter",
    1,
    4,
    3,
    [attack(1), attack(2), attack(2)],
    { cryo: true },
  ),
  external("E1-07", "Fighter", 2, 4, 3, [attack(1), attack(2), attack(3)]),
  external("E1-08", "Armored Grappler", 3, 4, 2, [
    attack(1),
    heal(1),
    attack(4),
  ]),
  external("E1-09", "Amoeba", 0, 8, 2, [heal(2), heal(2), attack(5)], {
    noRockets: true,
  }),
  external("E1-10", "Meteoroid", 0, 5, 5, [null, null, attack("hp")], {
    noRockets: true,
  }),
  external("E2-01", "Kamikaze", 2, 5, 4, [
    [change("speed", 1), { type: "set", stat: "shield", amount: 1 }],
    [change("speed", 1), { type: "set", stat: "shield", amount: 0 }],
    attack(6),
  ]),
  external(
    "E2-04",
    "Swarm",
    0,
    3,
    2,
    [
      attack(1),
      [attack(2), attack(1, "other")],
      [attack(3), attack(2, "other")],
    ],
    { damageCap: 1, noRockets: true },
  ),
  external(
    "E2-05",
    "Jellyfish",
    -2,
    13,
    2,
    [
      [attack(1, "all"), heal("half")],
      [attack(1, "all"), heal("half")],
      attack(2, "all"),
    ],
    { noRockets: true },
  ),
  external(
    "E2-07",
    "Minor Asteroid",
    0,
    7,
    4,
    [change("fragments", 1), change("fragments", 1), attack("hp")],
    { noRockets: true, asteroid: 1 },
  ),
  external("SE1-01", "Frigate", 2, 7, 2, [attack(2), attack(3), attack(4)]),
  external("SE1-02", "Man-of-War", 2, 9, 1, [
    [attack(2), change("speed", 1)],
    [attack(3), change("shield", 1)],
    attack(3),
  ]),
  external(
    "SE1-03",
    "Leviathan Tanker",
    3,
    8,
    2,
    [attack(2), [attack(2), heal(2)], attack(2)],
    { deathSplash: 1 },
  ),
  external(
    "SE1-04",
    "Pulse Satellite",
    2,
    4,
    3,
    [attack(1, "all"), attack(2, "all"), attack(3, "all")],
    { maxTargetRange: 2 },
  ),
  external(
    "SE1-05",
    "Cryoshield Frigate",
    1,
    7,
    2,
    [attack(2), attack(3), attack(4)],
    { cryo: true },
  ),
  external(
    "SE1-06",
    "Interstellar Octopus",
    1,
    8,
    2,
    [
      { ...attack(1, "all"), ifDamaged: true },
      { ...attack(2, "all"), ifDamaged: true },
      attack("double-hp"),
    ],
    { noRockets: true },
  ),
  external(
    "SE1-07",
    "Maelstrom",
    3,
    8,
    2,
    [
      { type: "drain", system: "shield", zones: "all" },
      attack(2, "other"),
      attack(3, "other"),
    ],
    { pulseBreaksShield: true },
  ),
  external(
    "SE1-08",
    "Asteroid",
    0,
    9,
    3,
    [change("fragments", 1), change("fragments", 1), attack("hp")],
    { noRockets: true, asteroid: 2 },
  ),
  external(
    "SE2-04",
    "Nebula Crab",
    2,
    7,
    2,
    [
      { type: "set", stat: "shield", amount: 4 },
      [change("speed", 2), { type: "set", stat: "shield", amount: 2 }],
      attack(5, "lateral"),
    ],
    { noRockets: true },
  ),
  external(
    "SE2-06",
    "Major Asteroid",
    0,
    11,
    2,
    [change("fragments", 1), change("fragments", 1), attack("hp")],
    { noRockets: true, asteroid: 3 },
  ),
  external("E1-101", "Plasmatic Fighter", 2, 4, 3, [
    attack(1, "own", "plasma"),
    attack(1, "own", "plasma"),
    attack(2, "own", "plasma"),
  ]),
  external(
    "E1-102",
    "Spinning Saucer",
    4,
    3,
    3,
    [attack(1), attack(1), { ...attack(5), unlessFlag: "off-course" }],
    { rocketDeflects: true },
  ),
  external(
    "E2-103",
    "Megashield Destroyer",
    4,
    3,
    2,
    [
      attack(1, "own", "double"),
      attack(1, "own", "double"),
      attack(3, "own", "double"),
    ],
    { megashield: true },
  ),
  external("SE2-101", "Plasmatic Frigate", 2, 7, 2, [
    attack(2, "own", "plasma"),
    attack(2, "own", "plasma"),
    attack(4, "own", "plasma"),
  ]),
  external(
    "SE2-103",
    "Mother Swarm",
    1,
    6,
    2,
    [
      attack(1),
      [attack(2), attack(1, "other")],
      [attack(4), attack(3, "other")],
    ],
    { noRockets: true, damageCap: 2 },
  ),
];
export function threatById(id) {
  const card = THREATS.find((x) => x.id === id);
  if (!card) throw Error(`Threat not implemented: ${id}`);
  return structuredClone(card);
}

function internal(id, name, hp, speed, stations, repair, xyz, traits = {}) {
  return {
    ...external(id, name, 0, hp, speed, xyz),
    position: "internal",
    stations,
    repair,
    ...traits,
  };
}
THREATS.push(
  internal(
    "I1-01",
    "Skirmishers",
    1,
    3,
    ["red-upper"],
    "bots",
    [null, { type: "move", direction: "lift" }, attack(3)],
    { returnsFire: true },
  ),
  internal(
    "I1-02",
    "Skirmishers",
    1,
    3,
    ["blue-upper"],
    "bots",
    [null, { type: "move", direction: "lift" }, attack(3)],
    { returnsFire: true },
  ),
  internal("I1-03", "Saboteur", 1, 4, ["white-lower"], "bots", [
    { type: "move", direction: "blue" },
    { type: "drain-or-damage" },
    attack(2),
  ]),
  internal("I1-04", "Saboteur", 1, 4, ["white-lower"], "bots", [
    { type: "move", direction: "red" },
    { type: "drain-or-damage" },
    attack(2),
  ]),
  internal("I1-05", "Hacked Shields", 3, 2, ["blue-upper"], "B", [
    { type: "drain", system: "shield" },
    { type: "drain", system: "reactor" },
    attack(2),
  ]),
  internal("I1-06", "Hacked Shields", 3, 2, ["red-upper"], "B", [
    { type: "drain", system: "shield" },
    { type: "drain", system: "reactor" },
    attack(2),
  ]),
  internal(
    "I1-07",
    "Unstable Warheads",
    3,
    3,
    ["blue-lower"],
    "C",
    [null, null, attack("triple-hp")],
    { rocketHp: true },
  ),
);
THREATS.push(
  internal(
    "SI1-01",
    "Commandos",
    2,
    2,
    ["red-lower"],
    "bots",
    [
      { type: "move", direction: "lift" },
      [
        { type: "move", direction: "blue", ifDamaged: true },
        { ...attack(2), ifUndamaged: true },
      ],
      [{ type: "knockout", scope: "station" }, attack(4)],
    ],
    { returnsFire: true },
  ),
  internal(
    "SI1-02",
    "Commandos",
    2,
    2,
    ["blue-upper"],
    "bots",
    [
      { type: "move", direction: "lift" },
      [
        { type: "move", direction: "red", ifDamaged: true },
        { ...attack(2), ifUndamaged: true },
      ],
      [{ type: "knockout", scope: "station" }, attack(4)],
    ],
    { returnsFire: true },
  ),
  internal(
    "SI1-03",
    "Alien",
    2,
    2,
    ["white-lower"],
    "bots",
    [
      flag("grown"),
      [{ type: "move", direction: "lift" }, attack("crew")],
      { type: "destroy-ship" },
    ],
    { grows: true },
  ),
  internal("SI1-05", "Crossed Wires", 4, 3, ["white-upper"], "B", [
    [{ type: "fill-shield" }, { type: "leak", system: "reactor" }],
    { type: "leak", system: "shield" },
    { type: "leak", system: "reactor", zones: "all" },
  ]),
);
THREATS.push(
  external(
    "E2-02",
    "Scout",
    1,
    3,
    2,
    [
      flag("attack-aura"),
      { type: "advance-others" },
      attack(2, "own", "ignore-shield"),
    ],
    { noHeavy: true },
  ),
  external(
    "E2-03",
    "Phantom Fighter",
    3,
    3,
    3,
    [flag("revealed"), attack(2), attack(3)],
    { stealth: true, rocketImmune: true },
  ),
  external("E2-06", "Marauder", 1, 6, 3, [
    flag("shield-aura"),
    { type: "drain", system: "shield", zones: "all", amount: 1 },
    attack(4),
  ]),
  external(
    "SE2-01",
    "Behemoth",
    4,
    7,
    2,
    [
      { ...attack(2), belowDamage: 2 },
      { ...attack(3), belowDamage: 3 },
      { ...attack(6), belowDamage: 6 },
    ],
    { behemoth: true },
  ),
  external(
    "SE2-02",
    "Juggernaut",
    3,
    10,
    1,
    [
      [change("speed", 2), attack(2)],
      [change("speed", 2), attack(3)],
      attack(7),
    ],
    { rocketMagnet: true },
  ),
  external(
    "SE2-03",
    "Psionic Satellite",
    2,
    5,
    2,
    [
      { type: "delay", scope: "zone" },
      { type: "delay", scope: "all" },
      { type: "knockout", scope: "all" },
    ],
    { maxTargetRange: 2 },
  ),
  external(
    "SE2-05",
    "Nemesis",
    1,
    9,
    3,
    [
      [attack(1), { type: "self-damage", amount: 1 }],
      [attack(2), { type: "self-damage", amount: 2 }],
      { type: "destroy-ship" },
    ],
    { retaliates: true },
  ),
  internal("SI1-04", "Fissure", 2, 2, ["red-upper"], "space-bots", [
    flag("double-red"),
    flag("double-all"),
    { type: "destroy-ship" },
  ]),
  internal(
    "SI1-06",
    "Battlebot Uprising",
    4,
    2,
    ["blue-upper", "red-lower"],
    "C",
    [
      { type: "knockout", scope: "active-bots" },
      { type: "knockout", scope: "station" },
      { type: "knockout", scope: "except-bridge" },
    ],
    { multiRepairBonus: 1 },
  ),
  internal(
    "I2-03",
    "Troopers",
    2,
    2,
    ["red-upper"],
    "bots",
    [
      { type: "move", direction: "lift" },
      { type: "move", direction: "blue" },
      attack(4),
    ],
    { returnsFire: true },
  ),
  internal(
    "I2-04",
    "Troopers",
    2,
    2,
    ["blue-lower"],
    "bots",
    [
      { type: "move", direction: "lift" },
      { type: "move", direction: "red" },
      attack(4),
    ],
    { returnsFire: true },
  ),
  internal("I2-05", "Virus", 3, 3, ["white-upper"], "C", [
    { type: "drain", system: "reactor", zones: "all", amount: 1 },
    { type: "delay", scope: "all" },
    attack(1, "all"),
  ]),
  internal(
    "I2-06",
    "Overheated Reactor",
    3,
    2,
    ["white-lower"],
    "B",
    [attack("reactor"), { type: "fuel-lost" }, attack(3)],
    { deathKnockout: ["red-lower", "blue-lower"] },
  ),
  internal(
    "SI2-01",
    "Executioner",
    2,
    2,
    ["blue-upper"],
    "bots",
    [
      [
        { type: "move", direction: "red" },
        { type: "knockout", scope: "without-bots" },
      ],
      [
        { type: "move", direction: "lift" },
        { type: "knockout", scope: "without-bots" },
      ],
      attack(3),
    ],
    { returnsFire: true },
  ),
  internal(
    "SI2-02",
    "Seeker",
    2,
    2,
    ["white-upper"],
    "bots",
    [
      { type: "seek" },
      { type: "seek" },
      [attack(5), { type: "knockout", scope: "station" }],
    ],
    { returnsFire: true, deathKnocksAttacker: true, points: [6, 15] },
  ),
  internal(
    "SI2-03",
    "Power System Overload",
    7,
    3,
    ["red-lower", "white-lower", "blue-lower"],
    "B",
    [
      { type: "drain", system: "reactor", zones: "white", amount: 2 },
      { type: "drain", system: "reactor", zones: "all", amount: 1 },
      attack(3, "all"),
    ],
    { multiRepairBonus: 2 },
  ),
  internal(
    "SI2-04",
    "Contamination",
    3,
    2,
    ["red-upper", "blue-upper", "red-lower", "blue-lower"],
    "bots",
    [
      { type: "delay", scope: "station" },
      attack(1, "stations"),
      [{ type: "knockout", scope: "station" }, flag("lethal-entry")],
    ],
    { removeTokenOnHit: true },
  ),
  internal(
    "SI2-05",
    "Nuclear Device",
    1,
    4,
    ["white-lower"],
    "C",
    [change("speed", 1), change("speed", 1), { type: "destroy-ship" }],
    { simultaneousRepairs: 3 },
  ),
);
THREATS.push(
  internal(
    "I2-01",
    "Slime",
    2,
    2,
    ["blue-lower"],
    "bots",
    [
      { type: "remove-rocket" },
      { type: "slime-spread" },
      attack(2, "occupied"),
    ],
    { slime: "red" },
  ),
  internal(
    "I2-02",
    "Slime",
    2,
    2,
    ["red-lower"],
    "bots",
    [
      { type: "disable-stored-bots" },
      { type: "slime-spread" },
      attack(2, "occupied"),
    ],
    { slime: "blue" },
  ),
);

// The New Frontier component faces and rulebook appendix (see docs/components.md).
const phased = (normal, hidden, zones = "own", mode = "normal") => ({
  ...attack(normal, zones, mode),
  phasedAmount: hidden,
});
const jump = (direction) => ({ type: "jump", direction });
const call = (position, severity = "normal", zone = "own", extra = {}) => ({
  type: "call",
  position,
  severity,
  zone,
  ...extra,
});
const move = (direction) => ({ type: "move", direction });
THREATS.push(
  external(
    "E2-101",
    "Mini-Carrier",
    2,
    5,
    2,
    [attack(2), attack(3, "other"), attack(4, "all")],
    { carrier: 2 },
  ),
  external(
    "E2-102",
    "Phasing Fighter",
    2,
    4,
    3,
    [phased(1, 1), phased(2, 1), phased(3, 2)],
    { phasing: true },
  ),
  external(
    "E3-101",
    "Plasmatic Needleship",
    1,
    3,
    3,
    [
      attack(1, "own", "plasma"),
      attack(2, "own", "plasma"),
      attack(4, "own", "plasma"),
    ],
    { noHeavy: true },
  ),
  external(
    "E3-102",
    "Phasing Pulser",
    1,
    6,
    2,
    [phased(1, 0, "all"), phased(1, 1, "all"), phased(3, 2, "all")],
    { phasing: true },
  ),
  external(
    "E3-103",
    "Phasing Destroyer",
    2,
    5,
    2,
    [
      phased(1, 1, "own", "double"),
      phased(2, 1, "own", "double"),
      phased(3, 2, "own", "double"),
    ],
    { phasing: true },
  ),
  external(
    "E3-104",
    "Megashield Fighter",
    4,
    4,
    3,
    [attack(1), attack(2), attack(3)],
    { megashield: true },
  ),
  ...["left", "right"].map((direction, i) =>
    external(`E3-${105 + i}`, "Jumper", 1, 6, 3, [
      [jump(direction), attack(1)],
      [attack(1), jump(direction), attack(1)],
      [attack(3), jump(direction), attack(1)],
    ]),
  ),
  external(
    "E3-107",
    "Sealed Capsule",
    4,
    4,
    4,
    [
      [change("speed", 1), { type: "set", stat: "shield", amount: 3 }],
      change("speed", 1),
      call("internal", "normal", "internal", { undamagedSpeed: true }),
    ],
    { points: [0, 0] },
  ),
  external(
    "E3-108",
    "Polarized Fighter",
    1,
    4,
    3,
    [attack(1), attack(2), attack(4)],
    { polarized: true },
  ),
  external(
    "SE1-101",
    "Space Carrier",
    3,
    6,
    2,
    [attack(2), attack(3, "other"), attack(4, "all")],
    { carrier: 2 },
  ),
  external(
    "SE1-102",
    "Dimension Spider",
    0,
    13,
    1,
    [
      { type: "set", stat: "shield", amount: 1 },
      change("shield", 1),
      attack(4, "all"),
    ],
    { noRockets: true, web: true },
  ),
  external(
    "SE2-102",
    "Phasing Frigate",
    2,
    7,
    2,
    [phased(2, 1), phased(3, 2), phased(4, 3)],
    { phasing: true },
  ),
  external(
    "SE3-101",
    "Phasing Man-of-War",
    2,
    9,
    1,
    [
      [phased(2, 1), change("speed", 1)],
      [phased(3, 2), change("shield", 1)],
      phased(5, 4),
    ],
    { phasing: true },
  ),
  external(
    "SE3-102",
    "Megashield Man-of-War",
    5,
    7,
    1,
    [[attack(2), change("speed", 1)], attack(3), attack(5)],
    { megashield: true },
  ),
  external(
    "SE3-103",
    "Super-Carrier",
    5,
    13,
    2,
    [attack(2), attack(4, "other"), attack(5, "all")],
    { carrier: 2, spans: true },
  ),
  external(
    "SE3-104",
    "Transmitter Satellite",
    2,
    5,
    3,
    [
      call("internal"),
      { type: "advance-others", position: "internal" },
      { type: "knockout-delay", scope: "all" },
    ],
    { maxTargetRange: 2, points: [4, 8] },
  ),
  external(
    "SE3-105",
    "Overlord",
    5,
    14,
    2,
    [
      [{ type: "set", stat: "shield", amount: 4 }, call("external")],
      { type: "heal-others", position: "external", amount: 1 },
      { type: "destroy-ship" },
    ],
    { spans: true },
  ),
  external("SE3-106", "Leaper", 2, 7, 2, [
    [attack(1), jump("right"), attack(1)],
    [attack(2), jump("left"), attack(1)],
    [attack(4), jump("right"), attack(1)],
  ]),
  external(
    "SE3-107",
    "Planetoid",
    0,
    13,
    1,
    [change("fragments", 1), change("fragments", 1), attack("hp")],
    { asteroid: 4, noRockets: true, accelerates: 1 },
  ),
  external(
    "E3-109",
    "Energy Snake",
    3,
    6,
    4,
    [attack(1), attack(2), attack("reactor+1", "own", "direct")],
    { pulseBreaksShield: true, slowsWhenHit: 2, energyHeal: true },
  ),
  external(
    "SE3-108",
    "Energy Dragon",
    3,
    9,
    4,
    [attack(2), attack(3), attack("reactor+1", "all", "direct")],
    { pulseBreaksShield: true, slowsWhenHit: 2, energyHeal: true },
  ),
  external(
    "SE3-109",
    "Polarized Frigate",
    2,
    5,
    2,
    [attack(1), attack(3), attack(5)],
    { polarized: true },
  ),
  internal(
    "I1-101",
    "Central Laser Jam",
    2,
    2,
    ["white-upper"],
    "A",
    [
      { type: "drain", system: "reactor", amount: 1 },
      attack(1),
      [attack(3), attack(1, "lateral")],
    ],
    { finishEnergy: true },
  ),
  internal(
    "I2-101",
    "Power Pack Overload",
    4,
    3,
    ["red-lower", "blue-lower"],
    "A",
    [
      [{ type: "disable-stored-bots" }, { type: "remove-rocket" }],
      heal(1),
      [{ type: "knockout", scope: "station" }, attack(3, "stations")],
    ],
    { multiRepairBonus: 1 },
  ),
  internal(
    "I2-102",
    "Ninja",
    3,
    2,
    ["blue-lower"],
    "bots",
    [
      flag("poison-entry"),
      { type: "drain", system: "reactor", amount: 1 },
      { type: "poison-detonate" },
    ],
    { poison: true },
  ),
  internal(
    "I3-101",
    "Lateral Laser Jam",
    3,
    3,
    ["red-upper"],
    "A",
    [
      { type: "drain", system: "reactor", amount: 2 },
      attack(2),
      [attack(3), attack(2, "white"), { type: "opposite-damage", amount: 1 }],
    ],
    { finishEnergy: true, parityStation: true },
  ),
  internal(
    "I3-102",
    "Pulse Cannon Short Circuit",
    2,
    2,
    ["white-lower"],
    "A",
    [
      { type: "short-circuit", resource: "reactor" },
      { type: "short-circuit", resource: "fuel" },
      attack(1, "all", "shielded"),
    ],
    { inaccessibility: 1, shortCircuit: true },
  ),
  internal(
    "I3-103",
    "Reversed Shields",
    5,
    4,
    ["red-upper", "white-upper", "blue-upper"],
    "B",
    [flag("ignore-shields"), flag("reverse-shields"), attack(2, "all")],
    { loneRepair: 1 },
  ),
  internal(
    "I3-104",
    "Breached Airlock",
    3,
    4,
    ["red-upper"],
    "C",
    [
      flag("sealed-red"),
      [attack(1), flag("sealed-blue")],
      [attack(3), { type: "knockout", scope: "zone" }],
    ],
    { botsRepairBonus: 1 },
  ),
  ...[
    ["red-upper", "blue"],
    ["blue-lower", "red"],
  ].map(([station, direction], i) =>
    internal(
      `I3-${105 + i}`,
      "Phasing Troopers",
      2,
      2,
      [station],
      "bots",
      [{ ...move("lift"), onlyPhasedIn: true }, move(direction), phased(4, 3)],
      { phasing: true, returnsFire: true },
    ),
  ),
  internal(
    "I3-107",
    "Driller",
    2,
    3,
    ["blue-lower"],
    "bots",
    [
      [
        { type: "set", stat: "inaccessibility", amount: 0 },
        { type: "drill-move" },
      ],
      { type: "drill-move" },
      attack(4),
    ],
    { inaccessibility: 1 },
  ),
  internal("SI1-101", "Shambler", 2, 2, ["white-upper"], "bots", [
    { ...move("blue"), ifCrew: true },
    { type: "shambler" },
    attack(4),
  ]),
  internal(
    "SI2-101",
    "Phasing Anomaly",
    2,
    3,
    ["white-upper"],
    "C",
    [
      { type: "blind", zone: "white" },
      { type: "blind", zone: "lateral" },
      [{ type: "knockout", scope: "zone" }, attack(3)],
    ],
    { phasing: true, inaccessibility: 1 },
  ),
  internal(
    "SI2-102",
    "Phasing Mine Layer",
    2,
    2,
    ["blue-upper"],
    "bots",
    [
      [
        { type: "mine" },
        { type: "move", direction: "red", phasedDirection: "blue" },
      ],
      [{ type: "mine" }, move("lift")],
      [{ type: "mine" }, { type: "detonate-mines" }],
    ],
    { phasing: true, returnsFire: true },
  ),
  internal(
    "SI3-101",
    "Rabid Beast",
    2,
    2,
    ["blue-upper"],
    "bots",
    [
      [{ type: "infect" }, move("red"), move("red")],
      [{ type: "infect" }, move("lift"), move("blue")],
      [attack(4), { type: "infection-detonate" }],
    ],
    { returnsFire: true, infection: true },
  ),
  internal(
    "SI3-102",
    "Hidden Transmitter",
    3,
    3,
    ["blue-upper"],
    "C",
    [
      [
        { type: "set", stat: "inaccessibility", amount: 0 },
        call("external", "normal", "blue"),
      ],
      { type: "advance-zone", zone: "blue", amount: 1 },
      [{ type: "drain", system: "shield", zones: "blue" }, attack(4)],
    ],
    { inaccessibility: 1, points: [4, 8] },
  ),
  internal(
    "SI3-103",
    "Hidden Transmitter",
    3,
    2,
    ["red-lower"],
    "C",
    [
      [
        { type: "set", stat: "inaccessibility", amount: 0 },
        call("external", "normal", "red"),
      ],
      { type: "advance-zone", zone: "red", amount: 2 },
      [{ type: "drain", system: "reactor", zones: "red" }, attack(4)],
    ],
    { inaccessibility: 1, points: [4, 8] },
  ),
  internal(
    "SI3-104",
    "Space-Time Vortex",
    3,
    2,
    ["white-upper"],
    "C",
    [
      { type: "repeat-action" },
      { type: "swap-zones" },
      { type: "vortex-draw" },
    ],
    { swapDeckOnHit: true, vortex: true },
  ),
  internal(
    "SI3-105",
    "Siren",
    2,
    2,
    ["red-lower"],
    "bots",
    [
      { type: "knockout", scope: "alone" },
      { type: "knockout", scope: "group" },
      { type: "knockout", scope: "all" },
    ],
    { returnsFire: true, teleportsOnHit: "blue-lower" },
  ),
  internal(
    "SI3-106",
    "Cyber Gremlin",
    1,
    2,
    ["red-lower"],
    "bots",
    [
      { type: "absorb-reactor" },
      [{ type: "sabotage" }, move("blue")],
      { type: "sabotage" },
    ],
    { inaccessibility: 1, gremlin: true },
  ),
  internal(
    "SI3-107",
    "Parasite",
    1,
    2,
    [],
    "bots",
    [
      { type: "parasite-drain" },
      { type: "parasite-knockout" },
      { type: "parasite-attack" },
    ],
    { parasite: true, returnsFire: true, points: [8, 18] },
  ),
);
